### ISSUE TITLE
Reward Issue

### ISSUE THREAD

**Issue by OGNova** [OGNova/blobpoints#1]
https://hastebin.com/uhogivurep.js

Failing with this trace.

```
TypeError: Cannot read property 'points' of undefined
    at Award.cmdRew (C:\Users\OGNovuh\Desktop\Blob Points\Custodian Rework\base\Social.js:198:7)
    at Award.run (C:\Users\OGNovuh\Desktop\Blob Points\Custodian Rework\commands\Currency\award.js:26:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Uncaught Promise Error:  { DiscordAPIError: Cannot send an empty message
    at item.request.gen.end (C:\Users\OGNovuh\Desktop\Blob Points\Custodian Rework\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:71:65)
    at then (C:\Users\OGNovuh\Desktop\Blob Points\Custodian Rework\node_modules\snekfetch\src\index.js:204:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'DiscordAPIError',
  message: 'Cannot send an empty message',
  path: '/api/v7/channels/335951728560046080/messages',
  code: 50006 }
```

**Comment by ThaTiemsz** [comment]
```js
      const score = this.client.points.get(`${message.guild.id}-${user}`);
      score.points += amount;
```
Is there a key named `points` in the `points` Enmap?

**Comment by OGNova** [comment]
Yeah, the enmap itself is defined as points, and everything but reward/award and deduct works in terms of points.

**Comment by ThaTiemsz** [comment]
Change it to this:
```js
      let score = this.client.points.get(`${message.guild.id}-${user}`);
      score += amount;
```

**Comment by OGNova** [comment]
That throws an ESLint error: 
![image](https://user-images.githubusercontent.com/26777028/33399394-808e85f0-d520-11e7-9da4-1e761f87d093.png)

And then throws this error in the console
```
TypeError: Assignment to constant variable.
    at Award.cmdRew (C:\Users\OGNovuh\Desktop\Blob Points\Custodian Rework\base\Social.js:198:13)
    at Award.run (C:\Users\OGNovuh\Desktop\Blob Points\Custodian Rework\commands\Currency\award.js:26:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ThaTiemsz** [comment]
Did you forget to change `const` to `let` as I did in the code block?

**Comment by OGNova** [comment]
Ah, that'd be a problem, yeah

**Comment by OGNova** [comment]
Thanks so much!
